name: Format code using Prettier
on: [push, pull_request]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Generate token
        uses: tibdex/github-app-token@v1
        id: generate-token
        if: github.repository_owner == 'RIMOPA'
        continue-on-error: true
          
      - name: Prettify code (RIMOPA)
        if: steps.generate-token.outcome == 'success'
        uses: ScratchAddons/prettier_action@master
        with:
          prettier_options: --write .
          commit_message: Format code
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          
      - name: Prettify code (outside RIMOPA)
        if: steps.generate-token.outcome != 'success'
        uses: ScratchAddons/prettier_action@master
        with:
          prettier_options: --write .
          commit_message: Format code
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
